## AAUSAT libfreertos makefile

## Target name
TARGET = libfreertos.a

## Objects that must be built in order to archive
SOURCES = heap_3.c
SOURCES += croutine.c
SOURCES += event_groups.c
SOURCES += list.c
SOURCES += port.c
SOURCES += queue.c
SOURCES += tasks.c
SOURCES += timers.c

include ../../build/libgeneric.mk
